### ISSUE TITLE
HIBP commercial API

### ISSUE THREAD

**Issue by brycx** [brycx/checkpwn#13]
HIBP is moving to a paid version of its account API, which means that you now need to purchase an API key to make calls to its API (See the blogpost [here](https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/)). I will most likely not be purchasing such a key and will therefor not be able to test any features adding this.

If anybody is interested in this feature being added and willing to provide an API key for this, I would be willing to implement it.

The change to the commercial API does not affect the password API. In other words, you may still check for breached passwords with `checkpwn pass`.

**Comment by mdtro** [comment]
Hi @brycx I'm willing to provide the API key for this functionality.

**Comment by brycx** [comment]
Hi @mdtro 

That sounds great! I'm currently wrapping up some other things, but should be able to get started on implementing the feature pretty soon. Most of the functionality needed is already present. My initial plan is to have users store their API key as an environment variable, also adding a `checkpwn register` option to do so.

You can find my email on my GitHub profile, so you can send the API key there if you want.

**Comment by brycx** [comment]
Please let me know once you've sent the API key @mdtro.

**Comment by Kidman1670** [comment]
-Why you don't just make a method for normal user add their commercial key. 
-The cheapest key in HIBP is just about 4USD I remember, that is not expensive for normal user.

- I think that most people use your tool for purpose of OSINT collection, that can fetch a dozen requests a day. Hope someone buy 1 key and give free for other ones is very unreasonable
-I think your code is good. Please keep put a little effort to make it finished.

**Comment by brycx** [comment]
Update: @mdtro has been so kind as to provide an API key to re-enable the account-checking functionality. We are currently working on the re-implementation.
